# Generated by Django 3.0.4 on 2020-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_user_id_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
