# Generated by Django 3.0.4 on 2020-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
